### ISSUE TITLE
No execution when using ReSharper Build

### ISSUE THREAD

**Issue by SeriousM** [bennor/AutoT4#16]
JetBrains introduced ReSharper Build around 10.2015 which is a replacement for the classic MsBuild procedure. (https://blog.jetbrains.com/dotnet/2015/10/15/introducing-resharper-build/)

Would it be possible to support their build-hook?

**Comment by bennor** [comment]
AutoT4 is triggered by the events Visual Studio raises for a build. Because ReSharper Build circumvents VS's build process, these events aren't raised. As far as I can tell, they don't raise any of their own, so there's no way to know a build is taking place.

This means there's not really any way I can support it. 

_It may be possible to write a ReSharper plugin to do the same thing, but [their plugin development documentation](https://www.jetbrains.com/help/devguide/README.html) is a mess and well out of date._
